[customizations.installer.kickstart]
contents = """
graphical
"""

# [[customizations.user]]
# name = "cyrene"
# description = "Cyrene"
# groups = ["wheel"]
# password = "cyrene"

[customizations.timezone]
timezone = "Asia/Shanghai"

[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "us"
